export type TasSalesSchemaTableSpec = {
  name: string;
  requiredColumns: readonly string[];
  ddl: string;
};

export const TAS_SALES_SCHEMA_FOUNDATION_TABLES = [
  "users",
  "leads",
  "tas_vehicles",
  "tas_branches",
  "tas_conversations",
  "tas_sales_handovers",
] as const;

export const TAS_SALES_SCHEMA_TABLES: readonly TasSalesSchemaTableSpec[] = [
  {
    name: "tas_vehicle_interests",
    requiredColumns: [
      "id", "conversationId", "leadId", "vehicleId", "priority", "interestLevel",
      "notes", "rejectionReason", "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_vehicle_interests (
      id INT NOT NULL AUTO_INCREMENT,
      conversationId INT NULL,
      leadId INT NULL,
      vehicleId INT NOT NULL,
      priority ENUM('Primary','Alternative') NOT NULL DEFAULT 'Primary',
      interestLevel ENUM('Hot','Warm','Cold') NOT NULL DEFAULT 'Warm',
      notes TEXT NULL,
      rejectionReason TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      UNIQUE KEY ux_tas_vehicle_interests_lead_vehicle (leadId, vehicleId),
      KEY idx_tas_vehicle_interests_conversation (conversationId),
      KEY idx_tas_vehicle_interests_vehicle (vehicleId)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  {
    name: "tas_sales_quotations",
    requiredColumns: [
      "id", "conversationId", "leadId", "handoverId", "vehicleId", "createdByUserId", "status",
      "quotationNumber", "title", "templateId", "clientName", "clientPhone", "clientEmail",
      "vehicleSummary", "servicesDescription", "itemsJson", "vatPercent", "duration", "terms",
      "shareToken", "versionNumber", "parentQuotationId", "sentAt", "acceptedAt", "rejectedAt",
      "vehiclePrice", "discountAmount", "accessoriesAmount", "warrantyAmount", "totalAmount",
      "expiresAt", "notes", "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_sales_quotations (
      id INT NOT NULL AUTO_INCREMENT,
      conversationId INT NULL,
      leadId INT NULL,
      handoverId INT NULL,
      vehicleId INT NULL,
      createdByUserId INT NULL,
      status ENUM('Draft','Sent','Accepted','Rejected','Expired') NOT NULL DEFAULT 'Draft',
      quotationNumber VARCHAR(64) NULL,
      title VARCHAR(255) NULL,
      templateId VARCHAR(64) NULL,
      clientName VARCHAR(255) NULL,
      clientPhone VARCHAR(64) NULL,
      clientEmail VARCHAR(255) NULL,
      vehicleSummary TEXT NULL,
      servicesDescription TEXT NULL,
      itemsJson JSON NULL,
      vatPercent DECIMAL(5,2) NOT NULL DEFAULT 14.00,
      duration TEXT NULL,
      terms TEXT NULL,
      shareToken VARCHAR(80) NULL,
      versionNumber INT NOT NULL DEFAULT 1,
      parentQuotationId INT NULL,
      sentAt TIMESTAMP NULL,
      acceptedAt TIMESTAMP NULL,
      rejectedAt TIMESTAMP NULL,
      vehiclePrice DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      discountAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      accessoriesAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      warrantyAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      totalAmount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      expiresAt TIMESTAMP NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      KEY idx_tas_sales_quotations_handover (handoverId),
      KEY idx_tas_sales_quotations_lead (leadId),
      KEY idx_tas_sales_quotations_status (status),
      KEY idx_tas_sales_quotations_expires (expiresAt),
      UNIQUE KEY ux_tas_sales_quotations_number (quotationNumber),
      KEY idx_tas_sales_quotations_parent (parentQuotationId),
      UNIQUE KEY ux_tas_sales_quotations_share_token (shareToken)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  {
    name: "tas_test_drives",
    requiredColumns: [
      "id", "conversationId", "leadId", "handoverId", "vehicleId", "branchId", "assignedUserId",
      "scheduledAt", "status", "feedback", "notes", "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_test_drives (
      id INT NOT NULL AUTO_INCREMENT,
      conversationId INT NULL,
      leadId INT NULL,
      handoverId INT NULL,
      vehicleId INT NULL,
      branchId INT NULL,
      assignedUserId INT NULL,
      scheduledAt TIMESTAMP NOT NULL,
      status ENUM('Scheduled','Confirmed','Done','Cancelled','NoShow') NOT NULL DEFAULT 'Scheduled',
      feedback TEXT NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      KEY idx_tas_test_drives_handover (handoverId),
      KEY idx_tas_test_drives_assigned (assignedUserId),
      KEY idx_tas_test_drives_scheduled (scheduledAt),
      KEY idx_tas_test_drives_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  {
    name: "tas_sales_tasks",
    requiredColumns: [
      "id", "conversationId", "leadId", "handoverId", "assignedToUserId", "createdByUserId",
      "title", "priority", "status", "dueAt", "completedAt", "notes", "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_sales_tasks (
      id INT NOT NULL AUTO_INCREMENT,
      conversationId INT NULL,
      leadId INT NULL,
      handoverId INT NULL,
      assignedToUserId INT NULL,
      createdByUserId INT NULL,
      title VARCHAR(255) NOT NULL,
      priority ENUM('Low','Medium','High','Urgent') NOT NULL DEFAULT 'Medium',
      status ENUM('Open','Done','Cancelled') NOT NULL DEFAULT 'Open',
      dueAt TIMESTAMP NOT NULL,
      completedAt TIMESTAMP NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      KEY idx_tas_sales_tasks_handover (handoverId),
      KEY idx_tas_sales_tasks_assigned (assignedToUserId),
      KEY idx_tas_sales_tasks_due (dueAt),
      KEY idx_tas_sales_tasks_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  {
    name: "tas_trade_ins",
    requiredColumns: [
      "id", "conversationId", "leadId", "handoverId", "currentBrand", "currentModel", "modelYear",
      "vin", "mileage", "conditionStatus", "estimatedValue", "inspectionStatus", "status", "notes",
      "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_trade_ins (
      id INT NOT NULL AUTO_INCREMENT,
      conversationId INT NULL,
      leadId INT NULL,
      handoverId INT NULL,
      currentBrand VARCHAR(120) NOT NULL,
      currentModel VARCHAR(120) NOT NULL,
      modelYear INT NULL,
      vin VARCHAR(80) NULL,
      mileage INT NULL,
      conditionStatus VARCHAR(80) NULL,
      estimatedValue DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      inspectionStatus ENUM('Pending','Scheduled','Done','Rejected') NOT NULL DEFAULT 'Pending',
      status ENUM('New','Inspection','Pricing','Accepted','Rejected') NOT NULL DEFAULT 'New',
      notes TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      KEY idx_tas_trade_ins_handover (handoverId),
      KEY idx_tas_trade_ins_lead (leadId),
      KEY idx_tas_trade_ins_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  {
    name: "tas_vehicle_inventory",
    requiredColumns: [
      "id", "vehicleId", "vin", "branchId", "color", "status", "purchaseCost", "salePrice",
      "reservedForLeadId", "notes", "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_vehicle_inventory (
      id INT NOT NULL AUTO_INCREMENT,
      vehicleId INT NOT NULL,
      vin VARCHAR(80) NULL,
      branchId INT NULL,
      color VARCHAR(80) NULL,
      status ENUM('Available','Reserved','Sold','Maintenance') NOT NULL DEFAULT 'Available',
      purchaseCost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      salePrice DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      reservedForLeadId INT NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      UNIQUE KEY ux_tas_vehicle_inventory_vin (vin),
      KEY idx_tas_vehicle_inventory_vehicle (vehicleId),
      KEY idx_tas_vehicle_inventory_branch (branchId),
      KEY idx_tas_vehicle_inventory_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  {
    name: "tas_sales_finance_applications",
    requiredColumns: [
      "id", "conversationId", "leadId", "handoverId", "vehicleId", "quotationId", "createdByUserId",
      "bankName", "applicantName", "applicantPhone", "vehiclePrice", "downPayment", "termMonths",
      "annualInterestRatePct", "monthlyPayment", "status", "notes", "createdAt", "updatedAt",
    ],
    ddl: `CREATE TABLE IF NOT EXISTS tas_sales_finance_applications (
      id INT NOT NULL AUTO_INCREMENT,
      conversationId INT NULL,
      leadId INT NULL,
      handoverId INT NULL,
      vehicleId INT NULL,
      quotationId INT NULL,
      createdByUserId INT NULL,
      bankName VARCHAR(255) NULL,
      applicantName VARCHAR(255) NULL,
      applicantPhone VARCHAR(80) NULL,
      vehiclePrice DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      downPayment DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      termMonths INT NOT NULL DEFAULT 60,
      annualInterestRatePct DECIMAL(5,2) NOT NULL DEFAULT 0.00,
      monthlyPayment DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      status ENUM('Submitted','Pending','Approved','Rejected','Signed') NOT NULL DEFAULT 'Submitted',
      notes TEXT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      KEY idx_tas_sales_finance_handover (handoverId),
      KEY idx_tas_sales_finance_lead (leadId),
      KEY idx_tas_sales_finance_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
] as const;
